package:
  name: fake_maker
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'failed')}}

source:
  #git_url: https://github.com/jgmorrison/fake_maker.git
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - fake-factory

test:
  imports:
    - fake_maker

