package:
  name: fakemaker
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'failed')}}

source:
  #git_url: https://github.com/jgmorrison/fakemaker.git
  git_url: .

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - fakemaker

